const config = {
  NEXT_PUBILC_FIREBASE_API_KEY: process.env.NEXT_PUBILC_FIREBASE_API_KEY,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGE_SENDER_ID: process.env.FIREBASE_MESSAGE_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
};

export default config;
